### ISSUE TITLE
project status ?

### ISSUE THREAD

**Issue by rofl0r** [jcnelson/vdev#100]
there are no commits since 3 months - does that mean the project is already stable, or is it abandoned, or momentarily paused ?

**Comment by suedi** [comment]
Mr. Nelson has had no time to put into this project, Hopefully
his schedule will allow for more work here in the future.

This project is in a fairly stable state, I run it every day and it works fine.

What the project needs is for it to run on a dist like Devuan and get more users.

I tried to run vdev on devuan but couldn't get it to work but it was the first time I tried out
Devuan/debian so probably easier for people famliar with it.

I have seen mention of other efforts packaging it on devuan mailinglist

I have a live image with vdev setup on AlphaOS  if you ike to try it out

http://alphaos.tuxfamily.org/forum/viewtopic.php?f=4&t=1378

**Comment by rofl0r** [comment]
ok i think this commit here answers my question: https://github.com/jcnelson/vdev/commit/ceb7a6c4f44dec542dc1c3c3d5abd27dec7f3e0e i.e. project is dead.

**Comment by mckaygerhard** [comment]
a year ago vdev was good integrated in jessie iso on devuan, and there's a package in testing repo, 

sad to know that nobody can continue to this work, i have not enought skills to work in it, but if some help are need i send a status request at devuan, but knowing the "personallity" of some devuan administration sure the response will be like that commit ceb7a6c i.e. project is dead.
