### ISSUE TITLE
sysfs mount name

### ISSUE THREAD

**Issue by fbt** [jcnelson/vdev#24]
When you are scanning for sysfs, you expect the sysfs mount to be named 'sysfs' and nothing else.
Maybe search for the sysfs mount _type_ instead?

**Comment by jcnelson** [comment]
Yeah, ideally the code would use getmntent_r(3) instead of directly parsing /proc/mounts (wish I'd known about this function sooner).  Let me see what I can do...

**Comment by jcnelson** [comment]
Should be fixed as of 9a6fea7c2596359bbb92b073e1308a31a5f54bd6.

**Comment by fbt** [comment]
Yep, works now. Thanks!
