### ISSUE TITLE
mksquashfs syntax error.

### ISSUE THREAD

**Issue by fbt** [jcnelson/vdev#31]
On my system (Arch Linux), mksquashfs from squashfs-tools throws a syntax error when you do this:

    mksquashfs  -force-uid 0 -force-gid 0 "/home/fbt/git/pkg/vdev-git/src/vdev-git/build/lib/vdev/hwdb/hwdb.squashfs.dir" "/home/fbt/git/pkg/vdev-git/src/vdev-git/build/lib/vdev/hwdb/hwdb.squashfs"

It requires the options to go after the arguments, like this:

    mksquashfs "/home/fbt/git/pkg/vdev-git/src/vdev-git/build/lib/vdev/hwdb/hwdb.squashfs.dir" "/home/fbt/git/pkg/vdev-git/src/vdev-git/build/lib/vdev/hwdb/hwdb.squashfs" -force-uid 0 -force-gid 0

The syntax is this:

    SYNTAX:mksquashfs source1 source2 ...  dest [options] [-e list of exclude dirs/files]

If this is incompatible with other systems, I can just patch this, no big deal.

**Comment by jcnelson** [comment]
My bad.  I committed a fix as of 76da69c85bc41cdca8c3eda978eda25d100084fe.  Can you confirm that it works?

**Comment by fbt** [comment]
Yep, works.
