### ISSUE TITLE
[helpers] WARN: Could not find pvs in /sbin/pvs.

### ISSUE THREAD

**Issue by jaromil** [jcnelson/vdev#50]
It is not clear from the documentation where this tool should come from.
Searching Devuan packages doesn't helps either:

```
★ fork /run/vdev >apt-cache search pvs
ipvsadm - Linux Virtual Server support programs
collectd-core - statistics collection and monitoring daemon (core system)
system-config-lvm - utility for graphically configuring Logical Volumes
```

none of the packages above contains the tool.

**Comment by fbt** [comment]
It's the [lvm2](https://packages.debian.org/jessie/amd64/lvm2/filelist) package.

**Comment by jcnelson** [comment]
@jaromil I've updated the README to indicate that the lvm2 and iproute2 packages are runtime dependencies.

**Comment by jaromil** [comment]
thankyou! :^)
