### ISSUE TITLE
usergroup cdrom

### ISSUE THREAD

**Issue by suedi** [jcnelson/vdev#82]
I get a warning in vdevd.log:  

`/bin/chown: invalid group: 'root:cdrom'`

I am on Arch derivative and there seems to be no usergroup `cdrom` in spec.

https://wiki.archlinux.org/index.php/DeveloperWiki:UID_/_GID_Database

There is however usergroup `optical` with  gid 93 that probably is the same as `cdrom`, right?

I seek guidance on how to handle this issue.

Could the name of the usergroup be made a variable in optical.act?
If so it would be trivial to adapt to different systems.

As it is now I have to edit in optical.sh

**Comment by jcnelson** [comment]
Hi @suedi,

It's possible to pass custom environment variables to vdev actions via a .act file.  I just updated all the helpers to take a device's owner, group, and mode from the .act file (via environment variables), which should remove the need for you to modify the helper program directly.  See 98642d445a5439c4f7ff21b7a9f084333020a909

**Comment by suedi** [comment]
Confirmed working!      
 great :+1: 

closing...
