### ISSUE TITLE
update usage with coldplug-only info

### ISSUE THREAD

**Issue by suedi** [jcnelson/vdev#85]
I saw info about `--coldplug-only` was missing in usage message.

Are you going to keep `-1` ,`--once` also, it was my impression
you would not? 

I keep forgetting what it was so would be helpful to just do `vdevd --help` 
and find out. ( `-1` is very easy to remember so I hope you keep that,
-n is not as intuitive)

**Comment by jcnelson** [comment]
Yes, I intend to keep both options.  I'll add the relevant information to the `--help` section as well.

**Comment by suedi** [comment]
Just to push you to commit so I can close of this rather silly bug.
(a bit silly by me reporting it I mean)

in config.c-->vdev_config_usage()

```C
int vdev_config_usage( char const* progname ) {
   fprintf(stderr, "\
...
   -l, --log-file LOGFILE_PATH\n\
                  Path to which to log information.\n\
                  Pass 'syslog' to log to syslog, instead of a logfile.\n\
                  \n\
   -1, --once \n\
       --cold-plug \n\
                  Exit once all extant devices have been processed.\n\
                  \n\
   -f, --foreground\n\
                  Run in the foreground; do not daemonize.\n\
                  \n\
...
```
```

**Comment by jcnelson** [comment]
Not silly at all!  I can merge it directly, or if you want, you can send it as a PR and it'll reflect your contribution in the project's commit history.  Your call :)

**Comment by suedi** [comment]
I'll take the contribution - sent you a PR

closing...
