### ISSUE TITLE
LVM2 questions

### ISSUE THREAD

**Issue by parazyd** [jcnelson/vdev#92]
By reading the readme, I still don't understand... Is LVM2 supported in vdev yet or no?

**Comment by jcnelson** [comment]
LVM2 is supported as long as you have installed the LVM2 tools.  Vdev will not be able to set up logical volume directories symlinks without them (but it will otherwise detect and set up the individual disks).

**Comment by parazyd** [comment]
I see. Thank you for a swift reply!

**Comment by parazyd** [comment]
I see. Thank you for a swift reply!

**Comment by parazyd** [comment]
I see. Thank you for a swift reply!

**Comment by parazyd** [comment]
I see. Thank you for a swift reply!
